# Generated by Django 4.2.16 on 2025-07-20 14:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="receipts/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "png", "jpg", "jpeg", "txt"]
                            )
                        ],
                    ),
                ),
                ("vendor", models.CharField(max_length=255)),
                ("transaction_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Utilities", "UTILITIES"),
                            ("Groceries", "GROCERIES"),
                            ("Entertainment", "ENTERTAINMENT"),
                            ("Transportation", "TRANSPORTATION"),
                            ("Other", "OTHER"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["vendor"], name="receipts_re_vendor_e64069_idx"
                    ),
                    models.Index(
                        fields=["transaction_date"],
                        name="receipts_re_transac_24bf2c_idx",
                    ),
                    models.Index(
                        fields=["amount"], name="receipts_re_amount_3d9936_idx"
                    ),
                    models.Index(
                        fields=["category"], name="receipts_re_categor_2c0f41_idx"
                    ),
                ],
            },
        ),
    ]
