# Generated by Django 4.2.16 on 2025-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
